# -*- coding: utf-8 -*-
"""P26.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/196DnH_NsGSxFmKmQeN3WbPu4_2TS8dNZ
"""

def swap(string):
  start = string[0]
  end = string[-1]
  swapped_string = end + string[1:-1] + start
  print(swapped_string)
a=input("Enter a string: ")
swap(a)